In [1]:
import quik_ai as qa
import numpy as np
import pandas as pd

from importlib.metadata import version 
print('Quik-AI Version: %s' % version('quik_ai'))

Quik-AI Version: 1.1.0


In [2]:
# create the dataframe to store our data
df = pd.DataFrame()

# create number of rows and categories
n = 4
choices = ['A','B','C']

# create vector data
df['flt'] = np.arange(n)
df['str'] = np.random.choice(choices, n)
df['flt_arr'] = [x for x in np.arange(n * 3).reshape(-1, 3)]
df['str_arr'] = [x for x in np.repeat(choices, n, -1).reshape(-1, 3)]
df['flt_mat'] = [x for x in np.arange(n * 3 * 2).reshape(-1, 2, 3)]
df['str_mat'] = [x for x in np.repeat(choices, n * 2, -1).reshape(-1, 2, 3)]

# sample responses
df['resp_flt'] = np.arange(n)
df['resp_arr'] = [x for x in np.arange(n * 2).reshape(-1, 2)]
df['resp_mat'] = [x for x in np.arange(n * 1 * 2).reshape(-1, 1, 2)]

# print the data frame
df

flt str      flt_arr    str_arr                       flt_mat  \
0    0   A    [0, 1, 2]  [A, A, A]        [[0, 1, 2], [3, 4, 5]]   
1    1   A    [3, 4, 5]  [A, B, B]      [[6, 7, 8], [9, 10, 11]]   
2    2   C    [6, 7, 8]  [B, B, C]  [[12, 13, 14], [15, 16, 17]]   
3    3   A  [9, 10, 11]  [C, C, C]  [[18, 19, 20], [21, 22, 23]]   

                  str_mat  resp_flt resp_arr  resp_mat  
0  [[A, A, A], [A, A, A]]         0   [0, 1]  [[0, 1]]  
1  [[A, A, B], [B, B, B]]         1   [2, 3]  [[2, 3]]  
2  [[B, B, B], [B, C, C]]         2   [4, 5]  [[4, 5]]  
3  [[C, C, C], [C, C, C]]         3   [6, 7]  [[6, 7]]

In [3]:
# get the driver
driver = qa.Driver(df, None, None, batch_size=n)

# create the tensorflow dataset
tdf = driver.get_tensorflow_dataset(
    data=df, 
    input_names=df.columns, 
    response='resp_mat', 
    run_forever=False, 
    time_window=1, 
    hp=None, 
    shuffle=False
)

for x, y in tdf:
    print('Batched input tensors:\n')
    print(x)
    print('\nResponse tensors:\n')
    print(y)

Batched input tensors:

{'flt': <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [1.],
       [2.],
       [3.]], dtype=float32)>, 'str': <tf.Tensor: shape=(4, 1), dtype=string, numpy=
array([[b'A'],
       [b'A'],
       [b'C'],
       [b'A']], dtype=object)>, 'flt_arr': <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]], dtype=float32)>, 'str_arr': <tf.Tensor: shape=(4, 3), dtype=string, numpy=
array([[b'A', b'A', b'A'],
       [b'A', b'B', b'B'],
       [b'B', b'B', b'C'],
       [b'C', b'C', b'C']], dtype=object)>, 'flt_mat': <tf.Tensor: shape=(4, 2, 3), dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.]]], dtype=float32)>, 'str_mat': <tf.Tensor: shape=(4, 2, 3), dtype=string, numpy=
array([[[b'A', 

In [4]:
# this time we add a time series component
tdf = driver.get_tensorflow_dataset(
    data=df, 
    input_names=df.columns, 
    response='resp_flt', 
    run_forever=False, 
    time_window=3, 
    hp=None, 
    shuffle=False
)

for x, y in tdf:
    print('Batched input tensors:\n')
    print(x)
    print('\nResponse tensors:\n')
    print(y)

Batched input tensors:

{'flt': <tf.Tensor: shape=(4, 3, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [1.]],

       [[0.],
        [1.],
        [2.]],

       [[1.],
        [2.],
        [3.]]], dtype=float32)>, 'str': <tf.Tensor: shape=(4, 3, 1), dtype=string, numpy=
array([[[b'[UNK]'],
        [b'[UNK]'],
        [b'A']],

       [[b'[UNK]'],
        [b'A'],
        [b'A']],

       [[b'A'],
        [b'A'],
        [b'C']],

       [[b'A'],
        [b'C'],
        [b'A']]], dtype=object)>, 'flt_arr': <tf.Tensor: shape=(4, 3, 3), dtype=float32, numpy=
array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  1.,  2.]],

       [[ 0.,  0.,  0.],
        [ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>, 'str_arr': <tf.Tensor: shape=(4, 3, 3), dtype=string